---
services:
  postgres:
    image: postgres:17-alpine
    container_name: scrollic-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/DataBase.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - scrollic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


  adminer:
    image: adminer:5
    container_name: scrollic-adminer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - scrollic-network


  redis:
    image: redis:8.0-alpine
    container_name: scrollic-redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - scrollic-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  cassandra:
    image: cassandra:5.0
    container_name: scrollic-cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: scrollic-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 16
      CASSANDRA_SEEDS: cassandra
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    networks:
      - scrollic-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  cassandra-init:
    image: cassandra:5.0
    container_name: scrollic-cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./backend/CassDataBase.cql:/scripts/init.cql
    networks:
      - scrollic-network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Ожидание готовности Cassandra...";
        sleep 20;
        echo "Начало инициализации...";
        until cqlsh cassandra -f /scripts/init.cql; do
          echo "Cassandra еще не запустилась, \
            повторная попытка через 5 секунд...";
          sleep 5;
        done;
        echo "Инициализация Cassandra завершена!";


  kafka:
    image: apache/kafka:4.0.2
    container_name: scrollic-kafka
    ports:
      - "${KAFKA_PORT}:9092"
      - "${KAFKA_CONTROLLER_PORT}:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # PLAINTEXT://localhost:9092 для тестов
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Q"

      # Для разработки пока стоит true
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - scrollic-network
    healthcheck:
      test: ["CMD", "sh", "-c",
             "/opt/kafka/bin/kafka-broker-api-versions.sh \
              --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: scrollic-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: scrollic-dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_UI_READ_ONLY: false
    networks:
      - scrollic-network


  api-gateway:
    build: ./backend/APIGateway
    container_name: scrollic-api-gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      test-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      USER_SERVICE_URL: http://user-service:8001
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - scrollic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s


  user-service:
    build: ./backend/UserService
    container_name: scrollic-user-service
    ports:
      - "${USER_SERVICE_PORT}:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: 0
      REDIS_PASSWORD: ""
      SECRET_KEY: ${SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    networks:
      - scrollic-network
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request;
             urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s


volumes:
  pg_data:
  redis_data:
  cassandra_data:
  kafka_data:


networks:
  scrollic-network:
    name: scrollic-network
    driver: bridge
