spring:
  application:
    name: news-fetcher-service
  kafka:
    topic:
      news: ${KAFKA_NEWS_TOPIC_NAME:news-topic}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        enable.idempotence: true

news:
  fetch-interval: ${FETCHING_INTERVAL_MS:60000}
  apikey: ${GNEWS_APIKEY}
